#
# Other tags available at https://hub.docker.com/r/sphinxdoc/sphinx
#
FROM sphinxdoc/sphinx:7.1.2

#
# Install HTML theme 'sphinx_rtd_theme'.
# See: https://github.com/readthedocs/sphinx_rtd_theme
#
RUN pip install sphinx-rtd-theme
